vert-x3/vertx-web-site

README.md

Sorry for this small PR. I don't have push rights to master yet.

Added info about `mvn sass:watch` to README

---

src/site/javascripts/docs.js

Fixes #29
See twbs/bootstrap#12126

Fix position of sidebar in Safari

---

src/site/community/index.html

Signed-off-by: Johannes Schüth <git@jotschi.de>
My vert.x contribution:
https://github.com/vert-x3/vertx-maven-service-factory/pull/1
Thirdparty contribution:
http://raaftech.github.io/neo4vertx/ / various vert.x 3 module migrations

Add user to list of contributors

---

src/site/index.html

Added ruby example to front page

---

src/site/community/index.html

I've contributed with some bugfixes on apex
- https://github.com/vert-x3/vertx-apex/pull/52
- https://github.com/vert-x3/vertx-apex/pull/54

Added contributor Ferran Puig

---

src/site/community/index.html

Signed-off-by: Paulo Lopes <paulo@mlopes.net>

Added Paulo Lopes to the list of contributors

---

src/site/community/index.html

add contributor

---

src/site/community/index.html

Just added my data to the committer list.
Signed-off-by: Clement Escoffier <clement.escoffier@gmail.com>

Add myself to the committer list.

---

README.md
github.json
gulpfile.js
package.json
src-gen/main/community/contributors-gen.js
src/main/community/contributors.js
src/main/tasks/contributors.js
src/main/tasks/update-contributors.js
src/site/community/index.html

Sorry for the amount of code :-)

Added task to automatically generate list of contributors

---

src/site/docs/index.html

Added 'Docker support' section to docs page

---

src/main/templates/footer.html
src/site/community/index.html
src/site/docs/index.html
src/site/index.html
src/site/whos_using/index.html

@michel-kraemer Could you review this please?

Various updates to the web-site

---

src/site/blog/posts/vertx3-postgresql-json.md

Another post showing how to use postgres JSON the main code is here:
https://gist.github.com/pmlopes/47f7f02b0b102b5e68d8

example of postgres json type

---

src/site/index.html

Updated the groovy example to match the other examples and the content that is being sent.

Example Content Type Correction

---

README.md
gulpfile.js
src/main/templates/blog.html
src/main/templates/post.html
src/site/blog/posts/intro-series/post-01-beginning.md
src/site/blog/posts/intro-series/post-02-configuration.md
src/site/blog/posts/intro-series/post-03-vertx-web.md
src/site/blog/posts/intro-series/post-04-ut-it.md
src/site/blog/posts/vertx3-postgresql-json.md
src/site/blog/posts/vertx3-realtime-webapps.md
src/site/blog/posts/vertx3-says-hello-to-node-developers.md
src/site/blog/posts/vertx3-service-script.md
src/site/blog/posts/vertx3-web-easy-as-pi.md
src/site/stylesheets/docs.less
src/site/stylesheets/main.less

* Improved layout of main blog page and blog posts
* Some minor editorial fixes
* URL polishing
@cescoffier @pmlopes @vietj @purplefox Please review. Thanks!

Improved blog layout

---

src/main/community/contributors.js

changes for the contributor section of the website

added my twitter link, change size of avatar for nmcl to 80 pixels

---

src/site/blog/posts/vertx-3.1.0-release.md

@cescoffier @pmlopes @vietj Please review and if you want anything else added just say :)

3.1.0 release announcement

---

gulpfile.js
package.json
src/main/templates/blog.html
src/main/templates/blog_archives.html
src/main/templates/blog_sidebar.html
src/site/blog/archives/index.html
src/site/stylesheets/main.less

Add blog archives

---

src/site/blog/posts/vertx3-es6-back-to-the-future.md

This small post shows how to use the new JavaScript with Vert.x. It shows that our API is totally backward compatible and we can mix and match both ES5 and ES6 using a transpiler.

Blog post on using ES6 and Vert.x

---

src/main/materials/materials.js

Hi,
I'd like to contribute my talk about vert.x at Joker conference 2015 - https://www.youtube.com/watch?v=JRFwicUlwyI&list=PLVe-2wcL84b8x3krxqsYHwlmfb4kb8A4n&index=14.
Joker conference is an annual international java conference in Saint-Petersburg, Russia. More about the conference here - http://jokerconf.com/en/. 
My talk is in Russian. The talk is called "Vert.x: the application guide"  and covers some fundamentals of the toolkit in a form of a theatre play.
Best regards,
Vladimir Krasilschik.
https://www.linkedin.com/in/vladimirkrasilschik
vladimir.krasilschik@gmail.com

adding info about presentation at Joker 2015

---

src/main/materials/materials.js

This talk was given during the first edition of the Paris Vert.x User Group in December 2015. 
http://www.meetup.com/Paris-vert-x-Meetup/events/226587108/
This event was also filmed (talk in french) : https://www.youtube.com/watch?v=8iS660iVkZE

Add first presentation by Melusyn at the Paris Vert.x User Group #1

---

src/site/blog/posts/vertx-redeploy-in-eclipse.md

A blog post explaining how to use the redeploy feature in Eclipse.

[BLOG] Redeploy in Eclipse

---

src/site/docs/index.html
src/site/stylesheets/main.less

This makes the links much easier to read. I tried various combinations and this seems to be the most readable one. Further ideas to structure the page better are welcome.

Put links on docs page in tables

---

gulpfile.js
package.json
src/main/tasks/generate-distribution-info.js
src/main/templates/footer.html
src/main/templates/header.html
src/site/download/index.html
src/site/index.html
src/site/stylesheets/main.less

I'm always confused when I click the download link and am redirected to Bintray. A dedicated download page improves user experience.

Add download page

---

src/site/blog/posts/vertx-unit-and-hamcrest.md

A blog post explaining how Hamcrest and vert.x unit can be used together.

Blog post about hamcrest and vert.x unit.

---

src/site/blog/posts/vertx-blueprint.md

This blog post is an introduction to the Vert.x Blueprint project of GSOC 2016.

Blog post about the blueprint project

---

src/main/community/contributors.js

Update site to reflect I am maintaining the AMQP 1.0 components.
Part of #170

update maintainer details for the AMQP 1.0 components

---

src/site/blog/posts/oauth2-providers.md

blog about the recent work on oauth2

Create oauth2-providers.md post

---

src/site/gsoc/index.html

This is a WiP for discussion about GSoC 2017 the dealine is Feb 08.

gsoc 2017 ideas

---

src/site/blog/posts/2017-03-16-vertx-lang-scala.md

I added a blog-post to introduce the basics for Scala-usage.

Scala post

---

src/main/materials/materials.js

Added "Reactive Internet of Things : the Vert.x way" presentation

---

src/site/blog/posts/2017-04-14-vertx-serverless.md

@pmlopes - please review and let me know if you have any suggestions. thanks.

Serverless Vert.x Blog Post

---

src/site/docs/index.html

Resolving by directing the link to the readme page

Manual link for openshift S2I is broken

---

src/site/blog/posts/2015-09-14-writing-secure-vertx-web-apps.md

https://github.com/vert-x3/vertx-web-site/issues/229

Remove HttpOnly from CSRF protection guide

---

src/site/blog/posts/2017-11-14-vertx-graphql.md

Signed-off-by: Johannes Schüth <git@jotschi.de>

Add graphql blogpost

---

src/site/blog/posts/2017-12-15-tcp-client-using-vertx-kotlin-and-gradle-build.md

The links to gist used in this blog (for direct reviewing of code)
* [NetClientVerticle.kt](https://gist.github.com/usmansaleem/2a176a7b752fcb72f7f31964809696fe)
* [build.gradle](https://gist.github.com/usmansaleem/e723f25b827e0a925eaef2957a80132d)
* [logback.xml](https://gist.github.com/usmansaleem/750c6d1cad0721b52be2ff00f758fb9f)
* [.gitignore](https://gist.github.com/usmansaleem/b5838484a20cb8b08f236f2265ad7a8e)

Blog Post - TCP Client Using Vert.x Kotlin Gradle

---

src/site/blog/posts/2017-11-13-AWS-Lambda-and-Vertx-Framework-URL-Shortener-Backend.md

Blog post: AWS Lambda & Vertx Framework URL Shortener Backend

---

src/main/materials/materials.js

Adding Vert.x articles using Infinispan, recently published in DZone

Add DZone Vert.x and Infinispan published articles

---

src/site/community/index.html

New community channel policy

---

src/site/docs/index.html

Openshift2 no longer in use
Added examples link for Openshift3 S2I

Cloud docs section update

---

src/main/templates/footer.html

The website is GDPR compliant as no personal identifiable user information is tracked, however due to google analytics we do use cookies and we also must be compliant stating that cookies are used and allow users to opt-out.
This PR will add the banner in the bottom of the page and link to the google opt out tool.

Update footer to allow opt-out of cookies/gdpr

---

src/generated/community/contributors-gen.js
src/main/community/contributors.js

Add pavel to commiters

---

src/site/docs/index.html

fix docs typo

---

src/site/blog/posts/2018-08-20-the-first-step-rss-reader.md

The screenshot does not fit the page:
In the PR i have changed the screenshot resolution from 3490x2278 to 1012x661

Fix image size

---

src/site/blog/posts/2018-08-20-the-first-step-rss-reader.md

Changes:
* removed instruction, related to maual installation
* improved highlighting 
@vietj , can you review please?

Remove instructions related to manual install in the first step of RSS reader tutorial

---

src/site/blog/posts/2017-06-12-openapi3-vertx-web-support.md

I updated the old vertx & openapi blog post with new snippets and doc links

Updated vertx openapi blog post

---

src/site/blog/posts/2018-12-10-http-response-validation-web-client.md

Blog post about 3.6 new feature: response predicates

HTTP response validation with the Vert.x Web Client

---

src/generated/community/contributors-gen.js
src/main/community/contributors.js

Hi, I added myself to the contributors' list as @vietj told me.

Added gmariotti to the contributors list

---

src/site/index.html

* See https://github.com/vert-x3/vertx-lang-ruby/issues/41

Use more idiomatic syntax for the Ruby example

---

src/site/blog/posts/2019-07-26-vertx-junit5-web-client.md

Signed-off-by: francesco <francescoguard@gmail.com>

Added blog post about vertx-junit5-web-client

---

src/main/community/contributors.js

Add Billy Yuan as a committer

---

src/site/docs/index.html

https://github.com/eclipse-vertx/vertx-json-schema/issues/1

Added JSON Schema docs

---

src/site/docs/index.html

Polyglot DB2 Client
